"project_id_env": "DSI_GUIDE_CROWDIN_ID"
"api_token_env": "CROWDIN_TOKEN"
preserve_hierarchy: true

files:
  - source: /_pages/en_US/*.md
    translation: /_pages/%locale_with_underscore%/%original_file_name%
  - source: /_data/navigation/en_US.yml
    translation: /_data/navigation/%locale_with_underscore%.yml
